export default {
    //定位
   status:"",
   //存放用户搜索的地点
   AddressStatus:"",
    IndexObj:{
        code:0,
        data:[],
        message:""
    },
    SpotObj:{
        code:0,
        data:[],
        message:""
    },
    SpotAttObj:{
        code:0,
        data:[],
        message:""
    }
}